# Generated by Django 4.2.3 on 2023-07-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_user_soical_comment_is_reply_comment_relply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='relply',
            new_name='reply',
        ),
    ]
